name: New Project
description: New project needs to be created
title: "Create Project XXXXXXXX"
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        New project
  - type: textarea
    attributes:
      label: Content
      value: |
        ### Links

        ShotGrid: https://automatik-vfx.shotgunstudio.com/page/project_overview?project_id=1879
        File system: **London** `/mnt/projects/slingshot`

        ### Tasks

        - [x] Create ShotGrid project
        - [ ] Create on file system
        - [ ] Create default OCIO setup
        - [ ] Create default Delivery Packager setup

