# Reusable workflow to add any issues to the Pipeline project.
name: Add issue to project

on:
  workflow_call:

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/AutomatikVFX/projects/3
          github-token: ${{ secrets.ADD_ISSUE_TO_PROJECT_PAT }}
